### ISSUE TITLE
arduino-1.5/arduino-1.5_patch/hardware/panstamp/msp430/platform.txt is dangling link

### ISSUE THREAD

**Issue by mgehre** [panStamp/panstamp#2]
The file
https://github.com/panStamp/panstamp/blob/master/arduino-1.5/arduino-1.5_patch/hardware/panstamp/msp430/platform.txt
is a link to
/home/daniel/development/panstamp_git/arduino-1.5/arduino-1.5_patch/lin/platform.txt

**Comment by Nurislam05** [comment]
friends, hello everyone, help me find these tools, I will be very grateful. I can buy too if we have the ones we need👉   Anti Swap  API for Anti Swap

**Comment by Nurislam05** [comment]
Please write to us by mail here or to the 
official mail: 👉 info@lrco.io
